name: Build APK

# 1. Run the workflow when changes are pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ============================================================
      # 2. Checkout project
      # ============================================================
      - name: Checkout
        uses: actions/checkout@v4

      # ============================================================
      # 3. Install Node.js
      # ============================================================
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # ============================================================
      # 4. Install project dependencies
      # ============================================================
      - name: Install dependencies
        run: npm install

      # ============================================================
      # 5. Build Vue application
      # ============================================================
      - name: Build Vue app
        run: npm run build

      # ============================================================
      # 6. Sync Capacitor
      # ============================================================
      - name: Sync Capacitor
        run: npx cap sync android

           # ============================================================
      # 7. Setup Java
      # ============================================================
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # ============================================================
      # 8. Give Gradle execution permission
      # ============================================================
      - name: Make Gradle executable
        run: chmod +x android/gradlew

      # ============================================================
      # 9. Check Gradle environment
      # ============================================================
      - name: Check Gradle version
        working-directory: android
        run: ./gradlew --version

      # ============================================================
      # 10. Build APK
      # ============================================================
      - name: Build APK
        working-directory: android
        run: ./gradlew assembleDebug

      # ============================================================
      # 11. Upload APK
      # ============================================================
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: IonicPhotogallery-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          retention-days: 30